CREATE TABLE EMEMBER(
	NUM		NUMBER		NOT NULL,
	ID 		VARCHAR2(20) NOT NULL,
	PASSWORD	NUMBER NOT NULL,
	NICKNAME	VARCHAR2(20) NOT NULL,
	BIRTH		VARCHAR2(20),
	EMAIL		VARCHAR2(20),
	GENDER		VARCHAR2(20),
	REGDATE		VARCHAR2(20) DEFAULT SYSDATE,
	PHONE		VARCHAR2(20),
	CONSTRAINT	NUM_PK PRIMARY KEY(NUM),
	CONSTRAINT	NICK_UQ UNIQUE(NICKNAME),
	CONSTRAINT 	ID_UQ UNIQUE(ID)
);



--DROP TABLE EMEMBER;


CREATE SEQUENCE USER_SEQ
INCREMENT BY 1
START WITH 1;

INSERT INTO EMEMBER(NUM, ID, PASSWORD) 
VALUES(USER_SEQ.NEXTVAL, 'EUNHYE', 111);

DELETE From EMEMBER;

SELECT * FROM EMEMBER;

SELECT COUNT(id) FROM EMEMBER WHERE ID ='aa';

SELECT COUNT(id) FROM EMEMBER WHERE ID ='qq';
SELECT count(*) FROM EMEMBER 

SELECT COUNT(NICKNAME) FROM EMEMBER WHERE NICKNAME='cc';

SELECT NICKNAME FROM EMEMBER WHERE ID = 'aa';

SELECT PASSWORD FROM EMEMBER WHERE ID = 'aa';
select password from emember where id='22';

CREATE TABLE EBOARD(
	NUM			NUMBER NOT NULL,				--게시물 번호
	BNUM		NUMBER NOT NULL,				--게시판 번호
	BNAME		VARCHAR2(20) NOT NULL,		--게시판 이름
	BTITLE		VARCHAR2(100) NOT NULL,		--게시물 제목
	BCONTENT	VARCHAR2(500) NOT NULL,		-- 게시물 내용
	FNAME		VARCHAR2(50) ,		--파일 이름
	FPATH		VARCHAR2(100),		--파일경로
	WDATE		VARCHAR2(20) DEFAULT SYSDATE, 
	NOTICE		VARCHAR2(3),
	BVIEW		NUMBER DEFAULT 1,
	--WNUM		NUMBER NOT NULL,		--작성자 NO
	WNAME		VARCHAR2(20) NOT NULL,	-- 작성자 이름
	CONSTRAINT BNUM_PK PRIMARY KEY(NUM)
);

CREATE SEQUENCE BOARD_SEQ
INCREMENT BY 1
START WITH 1;


INSERT INTO EBOARD(NUM, BNUM ,BNAME, BTITLE, BCONTENT, WNAME)
VALUES(BOARD_SEQ.NEXTVAL, 1, 'BASIC', '게시글입니다.', '내용입니다.','으넹');

INSERT INTO EBOARD(NUM, BNUM ,BNAME, BTITLE, BCONTENT, FNAME, FPATH, NOTICE ,WNAME)
VALUES(BOARD_SEQ.NEXTVAL, 1, 'basic', '제목', '내용', 'fname', 'fpath' ,'no' ,'user');

DELETE EBOARD where NUM = '63';

UPDATE EBOARD()

SELECT * FROM EBOARD;

SELECT * FROM EBOARD WHERE NUM='64';

UPDATE EBOARD SET BTITLE='제목', BCONTENT='내용', FNAME='FNAME', FPATH='FPATH', NOTICE='NOT' WHERE NUM = '64';

--DROP TABLE EBOARD;
